<?php
/**
 * Payroll Module - CSV Export Handler
 * Export payroll data to CSV format
 */

require_once __DIR__ . '/../../includes/auth_check.php';
require_once __DIR__ . '/helpers.php';

// Check export permission
if (!authz_user_can($conn, 'payroll_master', 'export')) {
    http_response_code(403);
    die('Access Denied: You do not have permission to export payroll data');
}

$payroll_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
if (!$payroll_id) {
    http_response_code(400);
    die('Invalid payroll ID');
}

// Get payroll details
$payroll = get_payroll_by_id($conn, $payroll_id);
if (!$payroll) {
    http_response_code(404);
    die('Payroll not found');
}

// Get payroll records
$records = get_payroll_records($conn, $payroll_id);

// Generate filename
$month_display = date('M-Y', strtotime($payroll['month'] . '-01'));
$filename = 'Payroll_' . $month_display . '_' . date('YmdHis') . '.csv';

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

// Create output stream
$output = fopen('php://output', 'w');

// Write UTF-8 BOM for Excel compatibility
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// Write header information
fputcsv($output, ['Payroll Export']);
fputcsv($output, ['Month', format_month_display($payroll['month'])]);
fputcsv($output, ['Status', $payroll['status']]);
fputcsv($output, ['Total Employees', $payroll['employee_count']]);
fputcsv($output, ['Total Amount', format_currency($payroll['total_amount'])]);
fputcsv($output, ['Generated On', date('d M Y, h:i A', strtotime($payroll['created_at']))]);
fputcsv($output, ['Generated By', $payroll['created_by_name']]);
fputcsv($output, []);

// Write column headers
fputcsv($output, [
    'S.No',
    'Employee Code',
    'Employee Name',
    'Department',
    'Designation',
    'Total Days',
    'Present Days',
    'Attendance %',
    'Base Salary',
    'Allowances',
    'Reimbursements',
    'Bonus',
    'Gross Earnings',
    'Deductions',
    'Penalties',
    'Total Deductions',
    'Net Pay',
    'Payment Reference',
    'Payment Date',
    'Remarks'
]);

// Write data rows
$serial = 1;
foreach ($records as $record) {
    $gross_earnings = $record['base_salary'] + $record['allowances'] + $record['reimbursements'] + $record['bonus'];
    $total_deductions = $record['deductions'] + $record['penalties'];
    $attendance_percentage = $record['total_days'] > 0 ? round(($record['attendance_days'] / $record['total_days']) * 100, 2) : 0;
    
    fputcsv($output, [
        $serial++,
        $record['employee_code'],
        $record['employee_name'],
        $record['department'],
        $record['designation'],
        $record['total_days'],
        $record['attendance_days'],
        $attendance_percentage . '%',
        number_format($record['base_salary'], 2, '.', ''),
        number_format($record['allowances'], 2, '.', ''),
        number_format($record['reimbursements'], 2, '.', ''),
        number_format($record['bonus'], 2, '.', ''),
        number_format($gross_earnings, 2, '.', ''),
        number_format($record['deductions'], 2, '.', ''),
        number_format($record['penalties'], 2, '.', ''),
        number_format($total_deductions, 2, '.', ''),
        number_format($record['net_pay'], 2, '.', ''),
        $record['payment_ref'] ?? '',
        $record['payment_date'] ? date('d M Y', strtotime($record['payment_date'])) : '',
        $record['remarks'] ?? ''
    ]);
}

// Write summary
fputcsv($output, []);
fputcsv($output, ['SUMMARY']);
fputcsv($output, ['Total Employees', count($records)]);
fputcsv($output, ['Total Base Salary', number_format(array_sum(array_column($records, 'base_salary')), 2, '.', '')]);
fputcsv($output, ['Total Allowances', number_format(array_sum(array_column($records, 'allowances')), 2, '.', '')]);
fputcsv($output, ['Total Reimbursements', number_format(array_sum(array_column($records, 'reimbursements')), 2, '.', '')]);
fputcsv($output, ['Total Bonus', number_format(array_sum(array_column($records, 'bonus')), 2, '.', '')]);
fputcsv($output, ['Total Deductions', number_format(array_sum(array_column($records, 'deductions')), 2, '.', '')]);
fputcsv($output, ['Total Penalties', number_format(array_sum(array_column($records, 'penalties')), 2, '.', '')]);
fputcsv($output, ['NET TOTAL', number_format($payroll['total_amount'], 2, '.', '')]);

fclose($output);
exit;
?>
